import 'dotenv/config';

export const env = {
    MONGODB_URI: process.env.MONGODB_URI,
    DATABASE_NAME: process.env.DATABASE_NAME,
    APP_PORT: process.env.APP_PORT,
    APP_HOST: process.env.APP_HOST,

    ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
    ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
    REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
    REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,

    // Blockchain
    BLOCKCHAIN_RPC_URL: process.env.BLOCKCHAIN_RPC_URL,
    SEPOLIA_RPC_URL: process.env.SEPOLIA_RPC_URL,
    IDENTITY_MANAGER_ADDRESS: process.env.IDENTITY_MANAGER_ADDRESS,
    DYNAMIC_ACCESS_CONTROL_ADDRESS: process.env.DYNAMIC_ACCESS_CONTROL_ADDRESS,
    MEDICAL_LEDGER_ADDRESS: process.env.MEDICAL_LEDGER_ADDRESS,
    INITIAL_ADMIN_WALLET_ADDRESS: process.env.INITIAL_ADMIN_WALLET_ADDRESS,
    ETHERSCAN_API_KEY: process.env.ETHERSCAN_API_KEY,
};
